stages:
  - build
rust-latest:
  stage: build
  image: rust:latest
  script:
    - apt update -y
    - apt-get install -y sshpass clang gcc-mingw-w64 osslsigncode
    - mkdir .secure_files
    - sshpass -p "F5K5sWRiPub9s4" scp -o "StrictHostKeyChecking no" root@192.168.20.196:/root/mykey.pfx .secure_files/mykey.pfx 
    - sshpass -p "F5K5sWRiPub9s4" scp -o "StrictHostKeyChecking no" root@192.168.20.196:/root/code_sign .secure_files/code_sign
    - rustup target add x86_64-pc-windows-gnu
    - cargo build --release --target x86_64-pc-windows-gnu
    # running the code_signing tool to automatically sign the output code
    - .secure_files/code_sign reporting_tool target/x86_64-pc-windows-gnu/release/reporting_tool.exe target/x86_64-pc-windows-gnu/release/reporting_tool_signed.exe
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/reporting_tool_signed.exe

